Vendor g/g@6dc0856
gardener/gardener-extension-shoot-cert-service pull request #57
Opened 2021-01-15 09:15 UTC by timuthy

**How to categorize this PR?**

/area TODO
/kind TODO
/priority normal

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2021-01-15 13:54 UTC, MartinWeindel requested changes
lgtm, only one typo to fix: `leadereletionid`

2021-01-15 13:54 UTC, MartinWeindel commented on charts/gardener-extension-shoot-cert-service/templates/_helpers.tpl
> +{{- define "leadereletionid" -}}
typo: leadereletion instead of leaderelection

2021-01-15 13:54 UTC, MartinWeindel commented on charts/gardener-extension-shoot-cert-service/templates/deployment.yaml
> +        - --leader-election-id={{ include "leadereletionid" . }}
type see above

2021-01-15 13:54 UTC, MartinWeindel commented on charts/gardener-extension-shoot-cert-service/templates/rbac.yaml
> +  - {{ include "leadereletionid" . }}
typo see above

2021-01-15 14:48 UTC, timuthy commented
Thanks for the quick review @MartinWeindel. I've updated the PR.

2021-01-18 07:03 UTC, MartinWeindel approved these changes
/lgtm

2021-01-18 07:04 UTC, merged