support custom issuer with external account binding and domain restrictions
gardener/gardener-extension-shoot-cert-service pull request #61
Opened 2021-02-22 16:18 UTC by MartinWeindel

**How to categorize this PR?**

/area control-plane
/kind enhancement
/priority normal

**What this PR does / why we need it**:
This PR provides adjustments for the v0.5.0 release of cert management:
- updated CRDs for issuers, certificates and new CRD for certificaterevocations
- support for custom issuer with external account binding
- support for domain restrictions in custom issuer spec
- support for providing private key for custom issuer via shoot resource reference

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature user
support for custom issuer with external account binding
```

```feature user
support for domain restrictions in custom issuer spec
```

```feature user
support for providing private key for custom issuer via shoot resource reference
```

2021-02-23 16:07 UTC, mandelsoft approved these changes

2021-02-23 16:11 UTC, MartinWeindel commented
/invite @timuthy

2021-02-24 15:05 UTC, timuthy commented on pkg/controller/actuator.go
> +				return "ref-" + ref.ResourceRef.Name
```suggestion
				return "v1beta1constants.ReferencedResourcesPrefix" + ref.ResourceRef.Name
```

2021-02-24 15:09 UTC, timuthy requested changes
Thank you, looks good in general. I wonder if we should now wait until all issuers get ready? I know we haven't done it yet but as we accept more user input the readiness of an issuer can really suffer and there will barely be no feedback since issuers are not reflected in the shoot cluster. WDYT?

2021-02-25 12:49 UTC, MartinWeindel commented on example/30-extension.yaml
> +          - private.sub1.my-domain.com
done

2021-02-25 12:50 UTC, MartinWeindel commented on pkg/controller/actuator.go
> +				return "ref-" + ref.ResourceRef.Name
fixed

2021-02-25 13:12 UTC, MartinWeindel commented
> I wonder if we should now wait until all issuers get ready? I know we haven't done it yet but as we accept more user input the readiness of an issuer can really suffer and there will barely be no feedback since issuers are not reflected in the shoot cluster. WDYT?

It's a good idea to check the status of all issuers. I wonder if it wouldn't make more sense to have some kind of health check? Anyhow this needs some more testing. I have one stakeholder who is waiting for the setting of the privateKey for a custom issue via a resource reference. May it is better to open an issue and deal with it in another PR?

2021-02-25 16:03 UTC, MartinWeindel commented
@timuthy 
Extending the health check was easier than expected.
The health check for the condition type `ControlPlaneHealthy` now also includes a status check of all issuers in the control plane. It reports issuer state and message if state is != 'Ready'

2021-02-26 07:48 UTC, timuthy approved these changes
/lgtm

Side note: We now have an indirect dependency to github.com/gardener/controller-manager-library which will on the long run cause conflicts with the Controller-Runtime and the K8s versions each lib uses. We should try to get rid of this again, but nothing I see critical for now.

2021-02-26 10:54 UTC, merged